import styles from "../styles/Home.module.css";
import Head from "next/head";
import HeaderComponent from "./HeaderComponent";
import FooterComponent from "./FooterComponent";
import React from "react";


function Layout({ children }: React.PropsWithChildren){
    return(
        <div className={styles.container}>
            <Head>
                <title>SillamaeSK</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>

            <HeaderComponent/>

            {children}

            <FooterComponent/>
        </div>


    )
}

export default Layout