import styles from "../styles/Home.module.css";
import Head from "next/head";
import HeaderComponent from "./HeaderComponent";
import FooterComponent from "./FooterComponent";
import React, {useEffect} from "react";
import Aos from 'aos'
import 'aos/dist/aos.css'

function Layout({ children }: React.PropsWithChildren){
    useEffect(()=>{
        Aos.init({duration: 1000})
    }, [])
    return(
        <div className={styles.container}>
            <Head>
                <title>SillamaeSK</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>

            <HeaderComponent/>

            {children}

            <FooterComponent/>
        </div>


    )
}

export default Layout