import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import HeaderComponent from "../components/HeaderComponent";
import ImageWithSchedule from "../components/MainPage/ImageWithSchedule";
import DescriptionNearNewsComponent from "../components/MainPage/DescriptionNearNewsComponent";
import NewsFacebookComponent from "../components/MainPage/NewsFacebookComponent";
import SideNavComponent from "../components/MainPage/SideNavComponent";
import ScheduleOnMainPageComponent from "../components/MainPage/ScheduleOnMainPageComponent";
import FooterComponent from "../components/FooterComponent";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
          <title>SillamaeSK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <HeaderComponent/>

        <main>
            <ImageWithSchedule/>

            <div className={styles.textAndNewsFrame}>
                <DescriptionNearNewsComponent/>
                <NewsFacebookComponent/>
            </div>

            <SideNavComponent/>

        </main>

        <ScheduleOnMainPageComponent/>

        <FooterComponent/>
    </div>


  )
}

export default Home
