import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import HeaderComponent from "./components/HeaderComponent";

import FooterComponent from "./components/FooterComponent";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>SillamaeSK</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HeaderComponent/>


            <FooterComponent/>
        </div>


    )
}

export default Home
